### ISSUE TITLE
Move team-culture.qmd?

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/series#19]
Looks like `team-culture.qmd` should be in `series/core-lessons/team-culture.qmd` instead of `series/team-culture.qmd`

Is that right @jules32 ?

**Comment by jules32** [comment]
Yes - now that we have the `core-lessons` subfolder there are several core chapters that need to be moved. So that the old links don't break, they will need [redirect aliases](https://quarto.org/docs/websites/website-navigation.html#redirects) in their yaml, following better-science.qmd as an example ([raw](https://raw.githubusercontent.com/Openscapes/series/main/core-lessons/better-science.qmd))

```
title: "Better science in less time"
aliases:
  - bsilt.html
  - /better-science.html    
```

This has been a lower priority but if you're able to update as you are working here that would be great! Thank you!

**Comment by jules32** [comment]
@stefaniebutland here's an example I did with `mindset.qmd`; when I added the NASA Champions link I also made the alias and moved the images ([commit to main](https://github.com/Openscapes/series/commit/05a78b14c91dee14f5b9849cc715b0aaf5606741))

**Comment by jules32** [comment]
Ha! That's why you (read: I) should always rebuild/test before pushing! I had to also update the `_quarto.yml`. Second commit to main: https://github.com/Openscapes/series/commit/119a423d3bbab1be92703199f3cab5424bf1cd48

**Comment by jules32** [comment]
Hi @stefaniebutland , I've learned what to do for our aliases: #26 

For your `team-culture.qmd` files, you'll want to add `../`. You'll also update the link in the `index.qmd` table (shows that separate warning on build. 

```
aliases: 
  - ../team-culture.html
```
